function Binutils1()
{
	mkdir -v ../binutils-build
	cd ../binutils-build

	CC="gcc -B/usr/bin/" ../binutils-2.17/configure \
	    --prefix=/tools --disable-nls --disable-werror

	make

	make install

	make -C ld clean
	make -C ld LIB_PATH=/tools/lib
	cp -v ld/ld-new /tools/bin

}

function GCC1()
{
	mkdir -v ../gcc-build
	cd ../gcc-build

	CC="gcc -B/usr/bin/" ../gcc-4.1.2/configure --prefix=/tools \
	    --with-local-prefix=/tools --disable-nls --enable-shared \
	    --enable-languages=c

	make bootstrap

	make install

	ln -vs gcc /tools/bin/cc
}

function Linux_API_Headers()
{
	make mrproper
	make headers_check
	make INSTALL_HDR_PATH=dest headers_install
	cp -rv dest/include/* /tools/include
}

function Glibc()
{
	mkdir -v ../glibc-build
	cd ../glibc-build

	../glibc-2.5.1/configure --prefix=/tools \
	    --disable-profile --enable-add-ons \
	    --enable-kernel=2.6.0 --with-binutils=/tools/bin \
	    --without-gd --with-headers=/tools/include \
	    --without-selinux

	make

	make check

	mkdir -v /tools/etc
	touch /tools/etc/ld.so.conf

	make install
}

function Adjusting_the_Toolchain()
{
	mv -v /tools/bin/{ld,ld-old}
	mv -v /tools/$(gcc -dumpmachine)/bin/{ld,ld-old}
	mv -v /tools/bin/{ld-new,ld}
	ln -sv /tools/bin/ld /tools/$(gcc -dumpmachine)/bin/ld

	gcc -dumpspecs | sed 's@^/lib/ld-linux.so.2@/tools&@g' \
	  > `dirname $(gcc -print-libgcc-file-name)`/specs

	GCC_INCLUDEDIR=`dirname $(gcc -print-libgcc-file-name)`/include &&
	find ${GCC_INCLUDEDIR}/* -maxdepth 0 -xtype d -exec rm -rvf '{}' \; &&
	rm -vf `grep -l "DO NOT EDIT THIS FILE" ${GCC_INCLUDEDIR}/*` &&
	unset GCC_INCLUDEDIR

}

function TestAdj()
{
	echo 'main(){}' > dummy.c
	cc dummy.c
	readelf -l a.out | grep ': /tools'

	rm -v dummy.c a.out
}

function Tcl()
{
	cd unix
	./configure --prefix=/tools

	make

	make install

	make install-private-headers

	ln -sv tclsh8.4 /tools/bin/tclsh
}

function Expect()
{
	patch -Np1 -i ../expect-5.43.0-spawn-1.patch
	cp configure{,.bak}
	sed 's:/usr/local/bin:/bin:' configure.bak > configure

	./configure --prefix=/tools --with-tcl=/tools/lib \
	  --with-tclinclude=/tools/include --with-x=no

	make

	make SCRIPTS="" install
}

function DejaGNU()
{
	./configure --prefix=/tools
	make install
}


function GCC_Pass_2()
{
	expect -c "spawn ls"

	cp -v gcc/Makefile.in{,.orig}
	sed 's@\./fixinc\.sh@-c true@' gcc/Makefile.in.orig > gcc/Makefile.in

	cp -v gcc/Makefile.in{,.tmp}
	sed 's/^XCFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in.tmp \
	  > gcc/Makefile.in

	patch -Np1 -i ../gcc-4.1.2-specs-1.patch

	mkdir -v ../gcc-build
	cd ../gcc-build

	../gcc-4.1.2/configure --prefix=/tools \
	    --with-local-prefix=/tools --enable-clocale=gnu \
	    --enable-shared --enable-threads=posix \
	    --enable-__cxa_atexit --enable-languages=c,c++ \
	    --disable-libstdcxx-pch

	make

	make -k check

	make install
}


function Binutils_Pass_2()
{
	mkdir -v ../binutils-build
	cd ../binutils-build

	../binutils-2.17/configure --prefix=/tools \
	    --disable-nls --with-lib-path=/tools/lib

	make

	make check

	make install

	make -C ld clean
	make -C ld LIB_PATH=/usr/lib:/lib
	cp -v ld/ld-new /tools/bin
}

function Ncurses()
{
	./configure --prefix=/tools --with-shared \
	    --without-debug --without-ada --enable-overwrite

	make

	make install
}

function Bash()
{
	patch -Np1 -i ../bash-3.2-fixes-5.patch

	./configure --prefix=/tools --without-bash-malloc

	make

	make install

	ln -vs bash /tools/bin/sh
}

function Bzip2()
{
	make
	make PREFIX=/tools install
}

function Coreutils()
{
	./configure --prefix=/tools
	make
	make install
	cp -v src/su /tools/bin/su-tools
}

function Diffutils()
{
	./configure --prefix=/tools
	make
	make install
}

function Findutils()
{
	./configure --prefix=/tools
	make
	make install
}

function Gawk()
{
	./configure --prefix=/tools

	cat >> config.h << "EOF"
	#define HAVE_LANGINFO_CODESET 1
	#define HAVE_LC_MESSAGES 1
	EOF

	make

	make install
}

function Gettext()
{
	cd gettext-tools
	./configure --prefix=/tools --disable-shared

	make -C gnulib-lib
	make -C src msgfmt

	cp -v src/msgfmt /tools/bin
}

function Grep()
{
	./configure --prefix=/tools \
	    --disable-perl-regexp

	make

	make install
}

function Gzip()
{
	./configure --prefix=/tools
	make
	make install
}

function Make_3_81()
{
	./configure --prefix=/tools
	make
	make install
}

function Patch_2_5_4()
{
	./configure --prefix=/tools
	make
	make install
}

function Perl_5_8_8()
{
	patch -Np1 -i ../perl-5.8.8-libc-2.patch

	./configure.gnu --prefix=/tools -Dstatic_ext='Data/Dumper Fcntl IO POSIX'

	make perl utilities

	cp -v perl pod/pod2man /tools/bin
	mkdir -pv /tools/lib/perl5/5.8.8
	cp -Rv lib/* /tools/lib/perl5/5.8.8
}

function Sed_4_1_5()
{
	./configure --prefix=/tools
	make
	make install
}

function Tar_1_18()
{
	./configure --prefix=/tools
	make
	make install
}

function Texinfo_4_9()
{
	./configure --prefix=/tools
	make
	make install
}

function Util_linux_2_12r()
{
	sed -i 's@/usr/include@/tools/include@g' configure

	./configure

	make -C lib

	make -C mount mount umount
	make -C text-utils more

	cp -v mount/{,u}mount text-utils/more /tools/bin
}

function Stripping()
{
	strip --strip-debug /tools/lib/*
	strip --strip-unneeded /tools/{,s}bin/*

	rm -rf /tools/{info,man}
}

function Changing_Ownership()
{
	chown -R root:root $LFS/tools
}

function VirtualKernelFS()
{
	mkdir -pv $LFS/{dev,proc,sys}

	mknod -m 600 $LFS/dev/console c 5 1
	mknod -m 666 $LFS/dev/null c 1 3

	mount -v --bind /dev $LFS/dev

	mount -vt devpts devpts $LFS/dev/pts
	mount -vt tmpfs shm $LFS/dev/shm
	mount -vt proc proc $LFS/proc
	mount -vt sysfs sysfs $LFS/sys
}

function Chroot_Env()
{
	chroot "$LFS" /tools/bin/env -i \
	    HOME=/root TERM="$TERM" PS1='\u:\w\$ ' \
	    PATH=/bin:/usr/bin:/sbin:/usr/sbin:/tools/bin \
	    /tools/bin/bash --login +h
}

function Creating_Directories()
{
	mkdir -pv /{bin,boot,etc/opt,home,lib,mnt,opt}
	mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
	install -dv -m 0750 /root
	install -dv -m 1777 /tmp /var/tmp
	mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
	mkdir -pv /usr/{,local/}share/{doc,info,locale,man}
	mkdir -v  /usr/{,local/}share/{misc,terminfo,zoneinfo}
	mkdir -pv /usr/{,local/}share/man/man{1..8}
	for dir in /usr /usr/local; do
		ln -sv share/{man,doc,info} $dir
	done
	mkdir -v /var/{lock,log,mail,run,spool}
	mkdir -pv /var/{opt,cache,lib/{misc,locate},local}
}

function Files_Symlinks()
{
	ln -sv /tools/bin/{bash,cat,echo,grep,pwd,stty} /bin
	ln -sv /tools/bin/perl /usr/bin
	ln -sv /tools/lib/libgcc_s.so{,.1} /usr/lib
	ln -sv /tools/lib/libstdc++.so{,.6} /usr/lib
	ln -sv bash /bin/sh

	touch /etc/mtab

	cat > /etc/passwd << "EOF"
	root:x:0:0:root:/root:/bin/bash
	nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
	EOF

	cat > /etc/group << "EOF"
	root:x:0:
	bin:x:1:
	sys:x:2:
	kmem:x:3:
	tty:x:4:
	tape:x:5:
	daemon:x:6:
	floppy:x:7:
	disk:x:8:
	lp:x:9:
	dialout:x:10:
	audio:x:11:
	video:x:12:
	utmp:x:13:
	usb:x:14:
	cdrom:x:15:
	mail:x:34:
	nogroup:x:99:
	EOF

	exec /tools/bin/bash --login +h

	touch /var/run/utmp /var/log/{btmp,lastlog,wtmp}
	chgrp -v utmp /var/run/utmp /var/log/lastlog
	chmod -v 664 /var/run/utmp /var/log/lastlog
}

function Linux_API_Headers2()
{
	sed -i '/scsi/d' include/Kbuild

	make mrproper
	make headers_check
	make INSTALL_HDR_PATH=dest headers_install
	cp -rv dest/include/* /usr/include
}

function Man_pages2()
{
	make install
}

function Glibc2()
{
	tar -xvf ../glibc-libidn-2.5.1.tar.gz
	mv glibc-libidn-2.5.1 libidn

	sed -i '/vi_VN.TCVN/d' localedata/SUPPORTED

	sed -i \
	's|libs -o|libs -L/usr/lib -Wl,-dynamic-linker=/lib/ld-linux.so.2 -o|' \
		scripts/test-installation.pl

	sed -i 's|@BASH@|/bin/bash|' elf/ldd.bash.in

	mkdir -v ../glibc-build
	cd ../glibc-build

	../glibc-2.5.1/configure --prefix=/usr \
	    --disable-profile --enable-add-ons \
	    --enable-kernel=2.6.0 --libexecdir=/usr/lib/glibc

	make

	make -k check 2>&1 | tee glibc-check-log
	grep Error glibc-check-log

	touch /etc/ld.so.conf

	make install

	mkdir -pv /usr/lib/locale
	localedef -i de_DE -f ISO-8859-1 de_DE
	localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
	localedef -i en_HK -f ISO-8859-1 en_HK
	localedef -i en_PH -f ISO-8859-1 en_PH
	localedef -i en_US -f ISO-8859-1 en_US
	localedef -i en_US -f UTF-8 en_US.UTF-8
	localedef -i es_MX -f ISO-8859-1 es_MX
	localedef -i fa_IR -f UTF-8 fa_IR
	localedef -i fr_FR -f ISO-8859-1 fr_FR
	localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
	localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
	localedef -i it_IT -f ISO-8859-1 it_IT
	localedef -i ja_JP -f EUC-JP ja_JP

	make localedata/install-locales

	cat > /etc/nsswitch.conf << "EOF"
	# Begin /etc/nsswitch.conf

	passwd: files
	group: files
	shadow: files

	hosts: files dns
	networks: files

	protocols: files
	services: files
	ethers: files
	rpc: files

	# End /etc/nsswitch.conf
	EOF

	tzselect

	cp -v --remove-destination /usr/share/zoneinfo/<xxx> \
	    /etc/localtime

	cat > /etc/ld.so.conf << "EOF"
	# Begin /etc/ld.so.conf

	/usr/local/lib
	/opt/lib

	# End /etc/ld.so.conf
	EOF

}

function Re_adjusting()
{
	mv -v /tools/bin/{ld,ld-old}
	mv -v /tools/$(gcc -dumpmachine)/bin/{ld,ld-old}
	mv -v /tools/bin/{ld-new,ld}
	ln -sv /tools/bin/ld /tools/$(gcc -dumpmachine)/bin/ld

	gcc -dumpspecs | sed \
	    -e 's@/tools/lib/ld-linux.so.2@/lib/ld-linux.so.2@g' \
	    -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
	    -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' > \
	    `dirname $(gcc --print-libgcc-file-name)`/specs

	echo 'main(){}' > dummy.c
	cc dummy.c -v -Wl,--verbose &> dummy.log
	readelf -l a.out | grep ': /lib'

	grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log

	grep -B1 '^ /usr/include' dummy.log

	grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'

	grep "/lib/libc.so.6 " dummy.log

	rm -v dummy.c a.out dummy.log
}

function Binutils2()
{
	expect -c "spawn ls"

	mkdir -v ../binutils-build
	cd ../binutils-build

	../binutils-2.17/configure --prefix=/usr \
	    --enable-shared

	make tooldir=/usr

	make check

	make tooldir=/usr install

	cp -v ../binutils-2.17/include/libiberty.h /usr/include
}

function GCC2()
{
	sed -i 's/install_to_$(INSTALL_DEST) //' libiberty/Makefile.in

	sed -i 's/^XCFLAGS =$/& -fomit-frame-pointer/' gcc/Makefile.in

	sed -i 's@\./fixinc\.sh@-c true@' gcc/Makefile.in

	sed -i 's/@have_mktemp_command@/yes/' gcc/gccbug.in

	mkdir -v ../gcc-build
	cd ../gcc-build

	../gcc-4.1.2/configure --prefix=/usr \
	    --libexecdir=/usr/lib --enable-shared \
	    --enable-threads=posix --enable-__cxa_atexit \
	    --enable-clocale=gnu --enable-languages=c,c++

	make

	make -k check

	../gcc-4.1.2/contrib/test_summary

	make install

	ln -sv ../usr/bin/cpp /lib

	ln -sv gcc /usr/bin/cc

	echo 'main(){}' > dummy.c
	cc dummy.c -v -Wl,--verbose &> dummy.log
	readelf -l a.out | grep ': /lib'

	grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log

	grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'

	grep "/lib/libc.so.6 " dummy.log

	grep found dummy.log

	rm -v dummy.c a.out dummy.log
}

function Berkeley_DB2()
{
	patch -Np1 -i ../db-4.5.20-fixes-1.patch

	cd build_unix
	../dist/configure --prefix=/usr --enable-compat185 --enable-cxx

	make

	make docdir=/usr/share/doc/db-4.5.20 install

	chown -Rv root:root /usr/share/doc/db-4.5.20
}

function Sed2()
{
	./configure --prefix=/usr --bindir=/bin --enable-html
	make
	make install
}

function  E2fsprogs2()
{
	sed -i -e 's@/bin/rm@/tools&@' lib/blkid/test_probe.in

	mkdir -v build
	cd build

	../configure --prefix=/usr --with-root-prefix="" \
	    --enable-elf-shlibs

	make

	make install

	make install-libs
}

function Coreutils2()
{
	patch -Np1 -i ../coreutils-6.9-uname-1.patch

	patch -Np1 -i ../coreutils-6.9-suppress_uptime_kill_su-1.patch

	patch -Np1 -i ../coreutils-6.9-i18n-1.patch

	chmod +x tests/sort/sort-mb-tests

	./configure --prefix=/usr

	make

	make NON_ROOT_USERNAME=nobody check-root

	echo "dummy:x:1000:nobody" >> /etc/group

	su-tools nobody -s /bin/bash -c "make RUN_EXPENSIVE_TESTS=yes check"

	sed -i '/dummy/d' /etc/group

	mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin
	mv -v /usr/bin/{false,hostname,ln,ls,mkdir,mknod,mv,pwd,readlink,rm} /bin
	mv -v /usr/bin/{rmdir,stty,sync,true,uname} /bin
	mv -v /usr/bin/chroot /usr/sbin

	mv -v /usr/bin/{head,sleep,nice} /bin
}

function Iana_Etc2()
{
	make
	make install
}

function M4_2()
{
	./configure --prefix=/usr
	make
	make install
}

function Bison2()
{
	./configure --prefix=/usr
	echo '#define YYENABLE_NLS 1' >> config.h
	make
	make install
}

function Ncurses2()
{
	patch -Np1 -i ../ncurses-5.6-coverity_fixes-1.patch

	./configure --prefix=/usr --with-shared --without-debug --enable-widec

	make

	make install

	chmod -v 644 /usr/lib/libncurses++w.a

	mv -v /usr/lib/libncursesw.so.5* /lib

	ln -sfv ../../lib/libncursesw.so.5 /usr/lib/libncursesw.so

	for lib in curses ncurses form panel menu ; do \
	    rm -vf /usr/lib/lib${lib}.so ; \
	    echo "INPUT(-l${lib}w)" >/usr/lib/lib${lib}.so ; \
	    ln -sfv lib${lib}w.a /usr/lib/lib${lib}.a ; \
	done
	ln -sfv libncurses++w.a /usr/lib/libncurses++.a

	rm -vf /usr/lib/libcursesw.so
	echo "INPUT(-lncursesw)" >/usr/lib/libcursesw.so
	ln -sfv libncurses.so /usr/lib/libcurses.so
	ln -sfv libncursesw.a /usr/lib/libcursesw.a
	ln -sfv libncurses.a /usr/lib/libcurses.a

	make distclean
	./configure --prefix=/usr --with-shared --without-normal \
	  --without-debug --without-cxx-binding
	make sources libs
	cp -av lib/lib*.so.5* /usr/lib
}

function Procps2()
{
	make
	make install
}

function Libtool2()
{
	./configure --prefix=/usr

	make
	make install
}

function Perl2()
{
	echo "127.0.0.1 localhost $(hostname)" > /etc/hosts

	./configure.gnu --prefix=/usr \
	    -Dman1dir=/usr/share/man/man1 \
	    -Dman3dir=/usr/share/man/man3 \
	    -Dpager="/usr/bin/less -isR"

		make
		make install
}

function Readline2()
{
	sed -i '/MV.*old/d' Makefile.in
	sed -i '/{OLDSUFF}/c:' support/shlib-install

	patch -Np1 -i ../readline-5.2-fixes-3.patch

	./configure --prefix=/usr --libdir=/lib

	make SHLIB_LIBS=-lncurses

	make install

	mv -v /lib/lib{readline,history}.a /usr/lib

	rm -v /lib/lib{readline,history}.so
	ln -sfv ../../lib/libreadline.so.5 /usr/lib/libreadline.so
	ln -sfv ../../lib/libhistory.so.5 /usr/lib/libhistory.so
}

function Zlib2()
{
	./configure --prefix=/usr --shared --libdir=/lib

	make

	make install

	rm -v /lib/libz.so
	ln -sfv ../../lib/libz.so.1.2.3 /usr/lib/libz.so

	make clean
	./configure --prefix=/usr
	make

	make install

	chmod -v 644 /usr/lib/libz.a
}

function Autoconf2()
{
	./configure --prefix=/usr

	make

	make install
}

function Automake2()
{
	./configure --prefix=/usr

	make

	make install
}

function Bash2()
{
	tar -xvf ../bash-doc-3.2.tar.gz
	sed -i "s|htmldir = @htmldir@|htmldir = /usr/share/doc/bash-3.2|" \
	    Makefile.in

	patch -Np1 -i ../bash-3.2-fixes-5.patch

	./configure --prefix=/usr --bindir=/bin \
	    --without-bash-malloc --with-installed-readline

	make

	sed -i 's/LANG/LC_ALL/' tests/intl.tests
	sed -i 's@tests@& </dev/tty@' tests/run-test
	chown -Rv nobody ./

	su-tools nobody -s /bin/bash -c "make tests"

	make install

	exec /bin/bash --login +h
}

function Bzip2_2()
{
	patch -Np1 -i ../bzip2-1.0.4-install_docs-1.patch

	make -f Makefile-libbz2_so
	make clean

	make

	make PREFIX=/usr install

	cp -v bzip2-shared /bin/bzip2
	cp -av libbz2.so* /lib
	ln -sv ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
	rm -v /usr/bin/{bunzip2,bzcat,bzip2}
	ln -sv bzip2 /bin/bunzip2
	ln -sv bzip2 /bin/bzcat
}

function Diffutils2()
{
	patch -Np1 -i ../diffutils-2.8.1-i18n-1.patch

	touch man/diff.1

	./configure --prefix=/usr

	make

	make install
}


function File2()
{
	./configure --prefix=/usr

	make

	make install
}

function  Findutils2()
{
	./configure --prefix=/usr --libexecdir=/usr/lib/findutils \
	    --localstatedir=/var/lib/locate

	make

	make install

	mv -v /usr/bin/find /bin
	sed -i -e 's/find:=${BINDIR}/find:=\/bin/' /usr/bin/updatedb
}

function Flex2()
{
	./configure --prefix=/usr

	make

	make install

	ln -sv libfl.a /usr/lib/libl.a

	cat > /usr/bin/lex << "EOF"
	#!/bin/sh
	# Begin /usr/bin/lex

	exec /usr/bin/flex -l "$@"

	# End /usr/bin/lex
	EOF
	chmod -v 755 /usr/bin/lex
}

function GRUB2()
{
	patch -Np1 -i ../grub-0.97-disk_geometry-1.patch

	./configure --prefix=/usr

	make

	make install
	mkdir -v /boot/grub
	cp -v /usr/lib/grub/i386-pc/stage{1,2} /boot/grub
}

function Gawk2()
{
	patch -Np1 -i ../gawk-3.1.5-segfault_fix-1.patch

	./configure --prefix=/usr --libexecdir=/usr/lib

	cat >> config.h << "EOF"
	#define HAVE_LANGINFO_CODESET 1
	#define HAVE_LC_MESSAGES 1
	EOF

	make

	make install
}

function Gettext2()
{
	./configure --prefix=/usr

	make

	make install
}

function Grep2()
{
	patch -Np1 -i ../grep-2.5.1a-redhat_fixes-2.patch

	chmod +x tests/fmbtest.sh

	./configure --prefix=/usr --bindir=/bin

	make

	make install
}

function Groff2()
{
	patch -Np1 -i ../groff-1.18.1.4-debian_fixes-1.patch

	sed -i -e 's/2010/002D/' -e 's/2212/002D/' \
	    -e 's/2018/0060/' -e 's/2019/0027/' font/devutf8/R.proto

	PAGE=<paper_size> ./configure --prefix=/usr --enable-multibyte

	make

	make install

	ln -sv eqn /usr/bin/geqn
	ln -sv tbl /usr/bin/gtbl
}

function Gzip2()
{
	./configure --prefix=/usr --bindir=/bin

	make

	make install

	mv -v /bin/{gzexe,uncompress,zcmp,zdiff,zegrep} /usr/bin
	mv -v /bin/{zfgrep,zforce,zgrep,zless,zmore,znew} /usr/bin
}

function  Inetutils2()
{
	patch -Np1 -i ../inetutils-1.5-no_server_man_pages-2.patch

	./configure --prefix=/usr --libexecdir=/usr/sbin \
	    --sysconfdir=/etc --localstatedir=/var \
	    --disable-ifconfig --disable-logger --disable-syslogd \
	    --disable-whois --disable-servers

	make

	make install

	mv -v /usr/bin/ping /bin
}

function IPRoute2_2()
{
	sed -i -e '/tc-bfifo.8/d' -e '/tc-pfifo.8/s/pbfifo/bfifo/' Makefile

	make SBINDIR=/sbin

	make SBINDIR=/sbin install

	mv -v /sbin/arpd /usr/sbin
}

function Kbd2()
{
	patch -Np1 -i ../kbd-1.12-backspace-1.patch

	patch -Np1 -i ../kbd-1.12-gcc4_fixes-1.patch

	./configure --datadir=/lib/kbd

	make

	make install

	mv -v /usr/bin/{kbd_mode,openvt,setfont} /bin
}

function Less2()
{
	./configure --prefix=/usr --sysconfdir=/etc

	make

	make install
}

function Make2()
{
	./configure --prefix=/usr

	make

	make install
}

function Man_DB2()
{
	mv man/de{_DE.88591,}
	mv man/es{_ES.88591,}
	mv man/it{_IT.88591,}
	mv man/ja{_JP.eucJP,}
	sed -i 's,\*_\*,??,' man/Makefile.in

	sed -i -e '\%\t/usr/man%d' -e '\%\t/usr/local/man%d' src/man_db.conf.in

	cat >> include/manconfig.h.in << "EOF"
	#define WEB_BROWSER "exec /usr/bin/lynx"
	#define COL "/usr/bin/col"
	#define VGRIND "/usr/bin/vgrind"
	#define GRAP "/usr/bin/grap"
	EOF

	patch -Np1 -i ../man-db-2.4.4-fixes-1.patch

	./configure --prefix=/usr --enable-mb-groff --disable-setuid

	make

	make install

	cat >> convert-mans << "EOF"
	#!/bin/sh -e
	FROM="$1"
	TO="$2"
	shift ; shift
	while [ $# -gt 0 ]
	do
		FILE="$1"
		shift
		iconv -f "$FROM" -t "$TO" "$FILE" >.tmp.iconv
		mv .tmp.iconv "$FILE"
	done
	EOF
	install -m755 convert-mans  /usr/bin
}

function Mktemp2()
{
	patch -Np1 -i ../mktemp-1.5-add_tempfile-3.patch

	./configure --prefix=/usr --with-libc

	make

	make install
	make install-tempfile
}

function Module_Init_Tools2()
{
	patch -Np1 -i ../module-init-tools-3.2.2-modprobe-1.patch

	./configure
	make check
	make distclean

	./configure --prefix=/ --enable-zlib

	make

	make INSTALL=install install
}

function Patch2()
{
	./configure --prefix=/usr

	make

	make install
}

function Psmisc2()
{
	./configure --prefix=/usr --exec-prefix=""

	make

	make install

	mv -v /bin/pstree* /usr/bin

	ln -sv killall /bin/pidof
}

function Shadow2()
{
	patch -Np1 -i ../shadow-4.0.18.1-useradd_fix-2.patch

	./configure --libdir=/lib --sysconfdir=/etc --enable-shared \
	    --without-selinux

	sed -i 's/groups$(EXEEXT) //' src/Makefile
	find man -name Makefile -exec sed -i 's/groups\.1 / /' {} \;

	sed -i -e 's/ ko//' -e 's/ zh_CN zh_TW//' man/Makefile

	for i in de es fi fr id it pt_BR; do
	    convert-mans UTF-8 ISO-8859-1 man/${i}/*.?
	done

	for i in cs hu pl; do
	    convert-mans UTF-8 ISO-8859-2 man/${i}/*.?
	done

	convert-mans UTF-8 EUC-JP man/ja/*.?
	convert-mans UTF-8 KOI8-R man/ru/*.?
	convert-mans UTF-8 ISO-8859-9 man/tr/*.?

	sed -i -e 's@#MD5_CRYPT_ENAB.no@MD5_CRYPT_ENAB yes@' \
	    -e 's@/var/spool/mail@/var/mail@' etc/login.defs

	make

	make install

	mv -v /usr/bin/passwd /bin

	mv -v /lib/libshadow.*a /usr/lib
	rm -v /lib/libshadow.so
	ln -sfv ../../lib/libshadow.so.0 /usr/lib/libshadow.so
}

function Sysklogd2()
{
	patch -Np1 -i ../sysklogd-1.4.1-fixes-2.patch

	patch -Np1 -i ../sysklogd-1.4.1-8bit-1.patch

	make

	make install
}

function Sysvinit2()
{
	sed -i 's@Sending processes@& configured via /etc/inittab@g' \
	    src/init.c

	make -C src

	make -C src install
}

function Tar2()
{
	./configure --prefix=/usr --bindir=/bin --libexecdir=/usr/sbin

	make

	make install
}

function Texinfo2()
{
	patch -Np1 -i ../texinfo-4.9-multibyte-1.patch

	patch -Np1 -i ../texinfo-4.9-tempfile_fix-1.patch

	./configure --prefix=/usr

	make

	make install

	make TEXMF=/usr/share/texmf install-tex

	cd /usr/share/info
	rm dir
	for f in *
	do install-info $f dir 2>/dev/null
	done
}

function Udev2()
{
	tar -xvf ../udev-config-6.3.tar.bz2

	install -dv /lib/{firmware,udev/devices/{pts,shm}}
	mknod -m0666 /lib/udev/devices/null c 1 3
	ln -sv /proc/self/fd /lib/udev/devices/fd
	ln -sv /proc/self/fd/0 /lib/udev/devices/stdin
	ln -sv /proc/self/fd/1 /lib/udev/devices/stdout
	ln -sv /proc/self/fd/2 /lib/udev/devices/stderr
	ln -sv /proc/kcore /lib/udev/devices/core

	make EXTRAS="`echo extras/*/`"

	make DESTDIR=/ EXTRAS="`echo extras/*/`" install

	cp -v etc/udev/rules.d/[0-9]* /etc/udev/rules.d/

	cd udev-config-6.3
	make install

	make install-doc

	make install-extra-doc

	cd ..
	install -m644 -v docs/writing_udev_rules/index.html \
	    /usr/share/doc/udev-113/index.html
}

function Util_linux2()
{
	sed -e 's@etc/adjtime@var/lib/hwclock/adjtime@g' \
	    -i $(grep -rl '/etc/adjtime' .)
	mkdir -pv /var/lib/hwclock

	patch -Np1 -i ../util-linux-2.12r-cramfs-1.patch
	patch -Np1 -i ../util-linux-2.12r-lseek-1.patch

	./configure

	make HAVE_KILL=yes HAVE_SLN=yes

	make HAVE_KILL=yes HAVE_SLN=yes install
}

function Vim2()
{
	patch -Np1 -i ../vim-7.1-fixes-1.patch

	patch -Np1 -i ../vim-7.1-mandir-1.patch

	echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h

	./configure --prefix=/usr --enable-multibyte

	make

	make install

	ln -sv vim /usr/bin/vi
	for L in "" fr it pl ru; do
	    ln -sv vim.1 /usr/share/man/$L/man1/vi.1
	done

	ln -sv ../vim/vim71/doc /usr/share/doc/vim-7.1
}





























