/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Jssdeep */

#ifndef _Included_Jssdeep
#define _Included_Jssdeep
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Jssdeep
 * Method:    fuzzy_hash_filename
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_Jssdeep_fuzzy_1hash_1filename
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     Jssdeep
 * Method:    fuzzy_hash_buf
 * Signature: ([BJLjava/lang/StringBuffer;)I
 */
JNIEXPORT jint JNICALL Java_Jssdeep_fuzzy_1hash_1buf
  (JNIEnv *, jobject, jbyteArray, jlong, jobject);

/*
 * Class:     Jssdeep
 * Method:    fuzzy_compare
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Jssdeep_fuzzy_1compare
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
