val a = (1 to 9)
val t1 = a.reduceLeft(_ * _)
val t2 = a.reduceLeft(_ + _)
val t3 = a.reduce(_ + _)
val b = Map("wang"->10,"zhi"->3,"long"->88)
val t4 = b.reduceByKey(_ + _)
println(t1)
println(t2)
println(t3)
