/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_suninfo_cloud_ndlp_bayes_JBayes */

#ifndef _Included_com_suninfo_cloud_ndlp_bayes_JBayes
#define _Included_com_suninfo_cloud_ndlp_bayes_JBayes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_suninfo_cloud_ndlp_bayes_JBayes
 * Method:    IsAttractiveContent
 * Signature: (Ljava/util/List;Lcom/suninfo/cloud/ndlp/bayes/BayesResult;)I
 */
JNIEXPORT jint JNICALL Java_com_suninfo_cloud_ndlp_bayes_JBayes_IsAttractiveContent
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_suninfo_cloud_ndlp_bayes_JBayes
 * Method:    LoadBayesModule
 * Signature: (Ljava/util/List;)I
 */
JNIEXPORT jint JNICALL Java_com_suninfo_cloud_ndlp_bayes_JBayes_LoadBayesModule
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
