all:
	g++ -shared -fPIC -o libjbayes.so -I/usr/lib/jvm/java-1.8.0/include -I/usr/lib/jvm/java-1.8.0/include/linux -I/usr/include/jsoncpp com_suninfo_cloud_ndlp_bayes_JBayes.cpp util.cpp Bayes2.cpp FileModel.cpp Model.cpp TFIDF.cpp CallBayes.cpp
