all:
	g++ -std=c++11 -g -O0 -o DNSmodel Main.cpp Result.cpp DataItem.cpp DNSModel.cpp UserProfile.cpp QueryByTime.cpp DataItem2Mysql.cpp config.cpp -I/usr/include/mysql -L/usr/lib64/mysql -lmysqlclient -ljsoncpp
clean:
	rm DNSmodel
